#!/bin/bash
# After the MP3D chain: re-sample poses with the storey-ceiling rule; scenes whose poses changed are
# wiped by resample_and_wipe.py and regenerated by the resume-safe stages.
cd /mnt/sdb/soundspaces/echoloc/echoloc_simulator && source env.sh && export ECHOLOC_DATASET=mp3d
L=logs
until grep -q "ALL DONE" $L/run_mp3d.log 2>/dev/null; do sleep 300; done
echo "[fix_mp3d] start $(date)"
$PY resample_and_wipe.py 0 2>&1 | grep "^\[resample\]"
JOBS=4 ./run_all.sh rgb 2>&1 | grep "^\[rgb\]"
JOBS=4 ./run_all.sh depthmaps 2>&1 | grep "^\[depthmaps\]"
WORKERS=12 ./run_all.sh depth 2>&1 | grep -c "^\[" | sed 's/^/[fix_mp3d] depth files: /'
WORKERS=12 ./run_all.sh desdf 2>&1 | grep -c "^\[" | sed 's/^/[fix_mp3d] desdf: /'
JOBS=6 THREADS=5 ./run_all.sh rir 2>&1 | grep "^\[rir\]"
LAYOUT=binaural JOBS=6 THREADS=5 ./run_all.sh rir 2>&1 | grep "^\[rir\]"
$PY write_dataset_meta.py 2>&1 | grep -v Warning | head -1
./run_all.sh validate --figs 0 2>&1 | grep -E "RESULT|FAIL" | sed 's/^/[fix_mp3d validate] /'
touch $L/mp3d_fixed.done; echo "[fix_mp3d] ALL DONE $(date)"
